# Generated by Django 5.0.7 on 2024-07-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='image',
            field=models.ImageField(upload_to='home/images/'),
        ),
    ]
