# Generated by Django 5.0.7 on 2024-10-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestions',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
