# Generated by Django 5.0.7 on 2024-08-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_items_json_orders_itemsjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itemsJson',
            new_name='items_json',
        ),
    ]
