# Generated by Django 5.0.7 on 2024-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_orders_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mf',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
