# Generated by Django 5.0.7 on 2024-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_signup_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contact',
        ),
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
