# Generated by Django 5.0.7 on 2024-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_signup_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
