# Generated by Django 5.0.7 on 2024-07-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_signup_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='phone_number',
            new_name='contact',
        ),
    ]
